#ifndef MESSAGESTYPES_H
#define MESSAGESTYPES_H

enum MessageType {JOIN, HEARTBEAT, SWREQ, SWRESP, JOINRESPONSE,
    FILEDATA, FILEDEL, FILEGET, FILEEND, ACK, MISSING,
    REPLICATE, INITREPLICATE, REPLICACK, VOTEACK, VOTE, FILESYSTEM};
enum LogType {JOINGROUP, UPDATE, FAIL, LEAVE, REMOVE, GOSSIPTO, GOSSIPFROM, BANDWIDTH, MEMBERS};

const static char *messageTypes[] =
{
    "JOIN",
    "HEARTBEAT",
    "SWREQ",
    "SWRESP",
    "JOINRESPONSE",
    "FILEDATA",
    "FILEDEL",
    "FILEGET",
    "FILEEND",
    "ACK",
    "MISSING",
    "REPLICATE",
    "INITREPLICATE",
    "REPLICACK",
    "VOTEACK",
    "VOTE",
    "FILESYSTEM",
};

#endif //MESSAGESTYPES_H
